### ISSUE TITLE
能否提供一下爬到的三字码的内容呢

### ISSUE THREAD

**Issue by buildyuan** [autofans/text03#1]
能否提供一下爬到的三字码的内容呢

**Comment by autofans** [comment]
你自己运行代码就得到内容了啊




------------------ 原始邮件 ------------------
发件人: "Yuan"<notifications@github.com>;
发送时间: 2019年10月28日(星期一) 下午4:40
收件人: "autofans/text03"<text03@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [autofans/text03] 能否提供一下爬到的三字码的内容呢 (#1)




能否提供一下爬到的三字码的内容呢
